### ISSUE TITLE
Checklist for release of-0.9

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#36]
- [x] Generate RC (release candidate) apk and upload it to Google Play Developer Console on Beta program and to releases on Github in order to make sure we won't have the openSLL problem again
- [x] Update android deploy instructions [here](https://github.com/Digitopia/PORTOphone-app/wiki/Deploy-instructions) to include Android Studio
- [x] Correctly working on all listed devices
- [x] Make sure at least @nunoh and @Oscar-Rodrigues can run and compile all versions of the app in their machines so it's faster to do any hotfix if needed (#35)
- [x] Do a last commit that **only** bumps the version numbers
- [x] Create final releases in Github
- [x] Upload to iTunes Store. Add info [here](https://github.com/Digitopia/PORTOphone-app/wiki/Deploy-instructions).
- [x] Celebrate :beers: :sparkler: 

---> [**Link to download APK for testing**](https://github.com/Digitopia/PORTOphone-app/releases/download/v1.3-android-rc/PORTOphone_v1.3-rc.apk) <---

**Android phones**
- [x] Samsung Galaxy S1with CyanogendMod @nunoh
- [x] Moto X (2013) Android v5.1 @nunoh
- [x] Samsung Galaxy Young 2 with Android v.2.3 @nunoh
- [x] Sony ST25i with Android 4.0.4 @p1nh0
- [x] Samsung Galaxy S3 with Android 4.3 @nunoh

**Android tablets**
- [x] @p1nh0 

**iOS phones**
- [ ] iPhone 6s 
- [ ] iPhone 6 @nunoh
- [ ] iPhone 6 @jasgomes 
- [ ] iPhone 5s @jasgomes 
- [ ] iPhone 5s @augusto666 
- [x] iPhone 5
- [ ] iPhone 4s @jasgomes 

**iOS tablets**
- [x] iPad 4th gen (iOS 9.1) @nunoh
- [x] iPad 4th gen (iOS 9.2) @nunoh
- [x] iPad @Oscar-Rodrigues

**Comment by nunoh** [comment]
@augusto666 do you get this email?

**Comment by augusto666** [comment]
@nunoh iphone 5s here

**Comment by p1nh0** [comment]
I have a Sony ST25i with Android 4.0.4

**Comment by nunoh** [comment]
@Digitopia/owners Guys, please update the first post with the devices that you have, in particular where you were mentioned. Comment below if you like. But the checkmarks are only to be ticked if the latest version is working correctly on the devices, which I doubt that you have done already :smile:, because to begin with I would have had to had shared the apk link with you which I haven't yet. Working on it though. I'll updated it here once I have it.

To edit the post, click the pencil like shown in the image:

<img width="1045" alt="screen_shot_2015-12-16_at_19_01_33" src="https://cloud.githubusercontent.com/assets/1161423/11850919/051d7ee2-a428-11e5-928d-15726865a9a5.png">

**Comment by jasgomes** [comment]
I can get a 5s, 4s and 6

**Comment by Oscar-Rodrigues** [comment]
@Digitopia/owners I don't have an Android tablet anymore. We should try to find someone who has, even if we just send them the final .apk before submitting it to Play Store.

**Comment by p1nh0** [comment]
Eu tenho um



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=4.0.4&source=email_footer_2] On Thu, Dec 17, 2015 at 4:29 PM, Óscar Rodrigues < notifications@github.com [notifications@github.com] > wrote:
@Digitopia/owners [https://github.com/orgs/Digitopia/teams/owners] I don't have an Android tablet anymore. We should try to find someone who has,
even if we just send them the final .apk before submitting it to Play Store.

—
Reply to this email directly or view it on GitHub
[https://github.com/Digitopia/PORTOphone-app/issues/36#issuecomment-165501467] .[https://github.com/notifications/beacon/ABg2TPGC1jEhp3ngo3KkhKHjc01MiIXaks5pQtpSgaJpZM4G1ylO.gif]

**Comment by nunoh** [comment]
@Digitopia/owners Android testers: We finally have an apk for testing! :tada: 

Please download it below and update it here (and in the top post) accordingly. 

---> [**Link to download APK for testing**](https://github.com/Digitopia/PORTOphone-app/releases/download/v1.3-android-rc/PORTOphone_v1.3-rc.apk) <---

FYI, the behaviour of the app should be pretty much 100% the same as before, the point is to try and break it and hopefully it won't. :smile: 

@jasgomes Think we have finally that warning of the OpenSSL under control so we should stop - if we still were - receiving emails about that. I've upload it to the Google Play Developer console since last Tuesday and there was no warning there whatsoever about that.

**Comment by jasgomes** [comment]
Perfect,

Please tell me when is ok to announce it to the general public



----------------
www.jasg.net

No dia 08/01/2016, às 16:53, Nuno Hespanhol <notifications@github.com> escreveu:

**Comment by nunoh** [comment]
Sure. Will do.

**Comment by nunoh** [comment]
Submitted to the App Store and releases created. Everything seems to be working now.
